- name: Install nginx
  yum: name=nginx state=latest
# - name: Enable default configuration
#   file: src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default state=link
- name: Configure nginx
  template: src=default.j2 dest=/etc/nginx/conf.d/default.conf
  notify:
    - restart nginx
- name: nginx start as bootup service
  service: name=nginx state=started
