- name: Install NTP
  yum: name=ntp state=latest
- name: Configure NTP
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
- name: Be sure NTPd is running and enabled
  service: name=ntpd state=started enabled=yes

- name: Add user
  user: name={{usergroup.user.name}} state=present password={{usergroup.user.password}} groups=wheel
